name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - run: echo "ðŸŽ‰ < hi"
      - run: echo "ðŸ§ < hello"
      - run: echo "ðŸ”Ž < hello"
      - run: echo "ðŸ’¡ < hello" 
      - run: echo "ðŸ–¥ï¸ < hello"
      - run: | 
          IP_ADDRESS=`curl ifconfig.io`
          echo $IP_ADDRESS
