name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - name: Prepare the ssh key.
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          USER_NAME: ${{ secrets.USER_NAME }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME}
          echo SSH OK
      - name: echo emoji.
      - run: echo "ðŸŽ‰ < hi"
      - run: echo "ðŸ§ < hello"
      - run: echo "ðŸ”Ž < hello"
      - run: echo "ðŸ’¡ < hello" 
      - run: echo "ðŸ–¥ï¸ < hello"
      - name: get WP data.
      - run: | 
          IP_ADDRESS=`curl ifconfig.io`
          echo $IP_ADDRESS
      - run: | 
          NEWS=`curl https://cpi-wp.tamsan-dev.com/wp-json/myapi/v1/news`
          echo $NEWS
