name: CPI Deploy Test
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - name: Run echo command.
      - run: echo "ğŸ§ < hello"
      - run: echo "ğŸ” < hello"
      - run: echo "ğŸ’¡ < hello" 
      - run: echo "ğŸ–¥ï¸ < hello"
